version: "3"

services:
  gitea:
    image: gitea/gitea:1.17.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db01:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - TZ=US/Central
    restart: always
    networks:
      - outside-network
      - internal-network
    volumes:
      - gitea:/data
    ports:
      # - "3000:3000"
      - "10022:22"
    depends_on:
      - db01
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.rule=Host(`gitea.unixfree.org`)"
      - "traefik.http.routers.gitea.tls.certresolver=lets-encr"
      - "traefik.http.routers.gitea.tls.domains[0].main=gitea.unixfree.org"
      - "traefik.http.services.gitea_service.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.gitea-headers.headers.framedeny=false"
      - "traefik.http.middlewares.gitea-headers.headers.sslredirect=true"
      - "traefik.http.middlewares.gitea-headers.headers.stsSeconds=155520011"
      - "traefik.http.middlewares.gitea-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.gitea-headers.headers.stsPreload=true"
      - "traefik.docker.network=outside-network"
  db01:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=US/Central
    networks:
      - internal-network
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  gitea:
    driver: local
  postgres:
    driver: local
networks:
  internal-network:
    external: false
  outside-network:
    external: true
