## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
providers:
  file:
    filename: /config/dynamic-config.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

global:
  # Send anonymous usage data
  sendAnonymousUsage: false
# Dynamic configuration

#tls:

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
